export CMAKE_PREFIX_PATH="$HOME/.local/"
export spdlog_DIR="$HOME/.local/lib/cmake/spdlog/"
export LEMON_DIR="$HOME/.local/share/lemon/cmake/"
export ortools_DIR="$HOME/.local/lib/cmake/ortools/"
export absl_DIR="$HOME/.local/lib/cmake/absl/"
export Protobuf_DIR="$HOME/.local/lib/cmake/protobuf/"
export scip_DIR="$HOME/.local/lib/cmake/scip/"
export ZLIB_DIR="$HOME/.local/lib/cmake/ZLIB/"
export highs_DIR="$HOME/.local/lib/cmake/highs/"
export utf8_range_DIR="$HOME/.local/lib/cmake/utf8_range/"
export re2_DIR="$HOME/.local/lib/cmake/re2/"
export Cbc_DIR="$HOME/.local/lib/cmake/Cbc/"
export Clp_DIR="$HOME/.local/lib/cmake/Clp/"
export Cgl_DIR="$HOME/.local/lib/cmake/Cgl/"

ARGS_OPENROAD="-DCMAKE_BUILD_TYPE=DEBUG -DASAN=ON -DTSAN=OFF -DUBSAN=ON -DENABLE_TESTS=OFF -DCOVERAGE=ON"
ARGS_YOSYS="CONFIG=gcc"

./build_openroad.sh --or_repo https://github.com/Faholan/OpenROAD.git --or_branch coverage --no_init -n -o --openroad-args "${ARGS_OPENROAD}" --yosys-args "${ARGS_YOSYS}"